name: Conjur-Policy-Audit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Policy via API
        shell: powershell 
        run: |
          # BARIS INI WAJIB: Memaksa Windows mengabaikan error sertifikat SSL
          [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
          
          $policy_content = Get-Content -Raw -Path "policies/scm.yml"
          $uri = "${{ vars.CONJUR_URL }}/policies/${{ vars.CONJUR_ACCOUNT }}/policy/root"
          $auth_uri = "${{ vars.CONJUR_URL }}/authn/${{ vars.CONJUR_ACCOUNT }}/${{ vars.CONJUR_USERNAME }}/authenticate"

          # Autentikasi untuk ambil token
          $token = Invoke-RestMethod -Method Post -Uri $auth_uri -Body '${{ secrets.CONJUR_API_KEY }}'
          $base64Token = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($token))

          $headers = @{
              "Authorization" = "Token token=`"$base64Token`""
          }

          # Kirim policy ke Conjur
          Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $policy_content -ContentType "text/plain"