name: Load Conjur Policy

on:
  push:

jobs:
  load-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conjur CLI
        run: |
          sudo apt update
          sudo apt install -y ruby-full
          sudo gem install conjur-cli
          sudo sed -i '2irequire "logger"' /usr/local/bin/conjur
          conjur --version

      - name: Authenticate & Load Policy
        env:
          url: ${{ secrets.CONJUR_URL }}
          account: conjur
          host_id: ${{ secrets.CONJUR_USERNAME }}
          api_key: ${{ secrets.CONJUR_API_KEY }}

        run: |
          echo "Initializing Conjur CLI..."

          conjur init \
            --url "$url" \
            --account "$CONJUR_ACCOUNT" \
            --force true

          echo "Logging in to Conjur..."

          conjur login \
            --id "host_id" \
            --password "$api_key"

          echo "Loading policy..."

          conjur policy load \
            -b root \
            -f policies/policy-branch.yml

          echo "Done!"