name: Load Conjur Policy

on:
  push:
  

jobs:
  load-policy:
    runs-on: self-hosted

    env:
      CONJUR_URL: ${{ vars.CONJUR_URL }}
      CONJUR_ACCOUNT: ${{ vars.CONJUR_ACCOUNT }}
      CONJUR_USERNAME: ${{ vars.CONJUR_USERNAME }}
      CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Install Conjur CLI
        run: |
          echo "Initializing Conjur CLI..."

      - name: Load Policy
        run: |
          Write-Host "Initializing Conjur CLI..."

          conjur init `
            --url "$env:CONJUR_URL" `
            --account "$env:CONJUR_ACCOUNT" `
            --force true

          Write-Host "Logging in..."

          conjur login `
            --id "$env:CONJUR_USERNAME" `
            --password "$env:CONJUR_API_KEY"

          Write-Host "Loading policy..."

          conjur policy load `
            -b root `
            -f policies/host-jenkins.yml

          Write-Host "Done!"