name: Conjur-Policy-Audit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Policy via API
        shell: pwsh
        run: |
          # Membaca isi file policy
          $policy_content = Get-Content -Raw -Path "policies/scm.yml"
          
          # Kirim ke Conjur API (Method Post untuk Load Policy)
          # Mengabaikan pengecekan SSL sementara agar tidak error di jaringan lokal
          $uri = "${{ vars.CONJUR_URL }}/policies/${{ vars.CONJUR_ACCOUNT }}/policy/root"
          
          $headers = @{
              "Authorization" = "Token token=`"$((Invoke-RestMethod -Method Post -Uri '${{ vars.CONJUR_URL }}/authn/${{ vars.CONJUR_ACCOUNT }}/${{ vars.CONJUR_USERNAME }}/authenticate' -Body '${{ secrets.CONJUR_API_KEY }}' -SkipCertificateCheck).ToString())`""
          }

          Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $policy_content -ContentType "text/plain" -SkipCertificateCheck