name: Load Conjur Policy

on:
  push:

jobs:
  load-policy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate & Load Policy to Conjur
        env:
          CONJUR_URL: ${{ vars.CONJUR_URL }}
          CONJUR_ACCOUNT: ${{ vars.CONJUR_ACCOUNT }}
          CONJUR_USERNAME: ${{ vars.CONJUR_USERNAME }}
          CONJUR_API_KEY: ${{ secrets.CONJUR_AUTHN_API_KEY }}
        run: |
          echo "Initializing Conjur CLI..."
          conjur init \
            --url "$CONJUR_URL" \
            --account "$CONJUR_ACCOUNT" \
            --force true

          echo "Logging in to Conjur..."
          conjur login \
            --id "$CONJUR_LOGIN" \
            --password "$CONJUR_API_KEY"

          echo "Loading policy to Conjur..."
          conjur policy load \
            -b root \
            -f policies/policy-branch.yml

          echo "Done!"